<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Web Page</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <nav>
        <ul class="main-nav">
            <a href="index.html">Home</a>
            <a href="details.html">Details</a>
            <a href="about.html">About</a>
            <a href="new-character-form.html">Add New Character</a>
        </ul>

        <header>
            <h1>Marvel Character Gallery</h1>
        </header>
    </nav>

    <div class="container">
        <div class="paragraph">
            <div class="column-image2">
                <img src="avengers.png" alt="Avengers" width="300" height="350">
            </div>

            <h3>About the Marvel Character Gallery</h3>

            <p>
                This is a a gallery of Marvel characters. You can browse through the characters, view their details, and
                even add new characters to the gallery.
                Use the search bar to find specific characters or filter them by their roles such as Hero, Villain,
                Civilian, or Ruler.

                The web page was designed to be straight-forward and simple to uderstand. The developer does NOT claim ownership
                of characters, concepts, or imagery presented. The developer DOES claim to be a superhero fan 
                (despite never reading a comic book and has only ever watching the movies).
            </p>
        </div>
    </div>

</body>

</html>